# Generated by Django 4.2.3 on 2023-07-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.CharField(default='SOME STRING', max_length=122, verbose_name='CREATED'),
        ),
    ]
